### ISSUE TITLE
编译时纠正submodules目录

### ISSUE THREAD

**Issue by xros** [KangLin/LunarCalendar#1]
纠正一下，
https://github.com/KangLin/LunarCalendar#use
这里submodules 应该是 3th_lib 不是 3th_libs 。否则qt不通过
编译环境qt 5.12.2， linux ubuntu 18.04.2 64bit。用的是qt自带的gcc。

另外，linux下编译完成后，再选择从 n月的某日到n+1月的某日，在同一个面板上操作时候，卡顿严重。
看了下cpu的使用情况，切换日期的时候，会很卡。系统单线程有个2秒钟左右的100%负载。是不是要优化一下。还是我cpu太烂。

**Comment by xros** [comment]
还有年月只有2000年以后的。以前的没有

**Comment by KangLin** [comment]
> 还有年月只有2000年以后的。以前的没有

因为QDATE支持的时间范围是从QDate(1, 1, 1)开始，不支持公元前时间，所以采用 从公元 1年1月1日开始，终止为 99999年12月31日。
也可调用下列接口设置：
    void SetMinimumDate(const QDate &date);
    void SetMaximumDate(const QDate &date);
    void SetDateRange(const QDate &min, const QDate &max);

**Comment by KangLin** [comment]
> 纠正一下，
> https://github.com/KangLin/LunarCalendar#use
> 这里submodules 应该是 3th_lib 不是 3th_libs 。否则qt不通过
> 编译环境qt 5.12.2， linux ubuntu 18.04.2 64bit。用的是qt自带的gcc。

这个你可能理解错了，它是其它应用程序使用本项目的使用方法。
编译的话，请看编译部分。

> 另外，linux下编译完成后，再选择从 n月的某日到n+1月的某日，在同一个面板上操作时候，卡顿严重。
> 看了下cpu的使用情况，切换日期的时候，会很卡。系统单线程有个2秒钟左右的100%负载。是不是要优化一下。还是我cpu太烂。

本项目中我已做了性能优化。做了缓存，月内日切换很性，月间切换要调用你的库。所以还是很慢。你的项目需要做下性能优化。
在我的机器上测试，getDayBySolar 函数平均调用时间为40ms。一个月日历一般为 40天左右。所以40*40=1600S.所以这样的性能不能够接受，还需要你优化。
本人机器配置：
CPU: Intel(R) Celeron(R) CPU G1820 @2.70GH
内存：4G


优化建议：https://github.com/yuangu/sxtwl_cpp/issues/13
