### ISSUE TITLE
ArchLinux上无法运行

### ISSUE THREAD

**Issue by zxp19821005** [KangLin/LunarCalendar#4]
`INSTALL_PATH:/opt/LunarCalendar
LD_LIBRARY_PATH:/opt/LunarCalendar/bin:/opt/LunarCalendar/lib:/opt/LunarCalendar/lib/x86_64-linux-gnu:
/opt/LunarCalendar/bin/LunarCalendarApp: error while loading shared libraries: libQt6StateMachine.so.6: cannot open shared object file: No such file or directory`

**Comment by KangLin** [comment]
- 你是自己编译的，还是用的安装包？
- 你的操作系统详细信息？
- Qt 依赖库没有安装。
sudo apt install libqt6scxml6

**Comment by zxp19821005** [comment]
非常感谢你的回复！
我用的是已经编译好的deb包。
操作系统是CachyOS x86_64
内核是6.3.1
桌面环境是KDE Plasma 5.27.4.1
当我安装了`qt6-scxml`后，问题解决。
谢谢！
